[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x67b3b7d84c1f95da18bfb29b5cca19e3c6e594eabafe043c1fb1237a7cead93c'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]